In [1]:
import pandas as pd

In [2]:
d1 = pd.read_csv(r"C:\Users\Mahoor Zehra\Downloads\archive (3)\googleplaystore.csv")

In [3]:
d1.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [5]:
d1.sample(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
6534,New York Mysteries (Full),GAME,4.5,514,5.9M,"5,000+",Paid,$6.99,Teen,Adventure,"June 4, 2018",1.0.36,4.0 and up
3737,Opera News - Trending news and videos,NEWS_AND_MAGAZINES,4.5,51684,8.5M,"10,000,000+",Free,0,Teen,News & Magazines,"July 31, 2018",4.2.2254.129147,Varies with device
7763,Battle Result Predictor for CR,TOOLS,4.2,7063,17M,"1,000,000+",Free,0,Everyone,Tools,"February 4, 2017",1.3.0,4.1 and up
9969,Texas Hold'em EV Calculator,TOOLS,3.7,6,1.3M,"1,000+",Free,0,Everyone,Tools,"November 8, 2015",1.0,2.3 and up
1488,"乐屋网: Buying a house, selling a house, renting ...",HOUSE_AND_HOME,3.7,2248,15M,"100,000+",Free,0,Everyone,House & Home,"August 3, 2018",v3.1.1,4.0 and up
9980,EvAk Smart Home,LIFESTYLE,NaN,14,Varies with device,500+,Free,0,Everyone,Lifestyle,"March 13, 2018",1.1.1,4.1 and up
6276,Oracle BI Mobile,BUSINESS,4.0,282,7.7M,"10,000+",Free,0,Everyone,Business,"August 1, 2018",20.0.0.0,6.0 and up
5136,Angelcare AH,MEDICAL,NaN,0,29M,50+,Free,0,Everyone,Medical,"October 6, 2017",300000.0.91,4.0.3 and up
4218,D+H Reaction Wall,GAME,NaN,0,Varies with device,1+,Paid,$0.99,Everyone,Arcade,"July 24, 2016",Varies with device,Varies with device
6098,GF - BF Chat Stories - Hindi English Convesation,FAMILY,4.1,32,4.1M,"10,000+",Free,0,Everyone,Education,"June 18, 2018",1.5,4.1 and up

In [6]:
d1.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

In [9]:
print(d1['Category'].unique())
d1['Category'].nunique()

<StringArray>
[     'ART_AND_DESIGN',   'AUTO_AND_VEHICLES',              'BEAUTY',
 'BOOKS_AND_REFERENCE',            'BUSINESS',              'COMICS',
       'COMMUNICATION',              'DATING',           'EDUCATION',
       'ENTERTAINMENT',              'EVENTS',             'FINANCE',
      'FOOD_AND_DRINK',  'HEALTH_AND_FITNESS',      'HOUSE_AND_HOME',
  'LIBRARIES_AND_DEMO',           'LIFESTYLE',                'GAME',
              'FAMILY',             'MEDICAL',              'SOCIAL',
            'SHOPPING',         'PHOTOGRAPHY',              'SPORTS',
    'TRAVEL_AND_LOCAL',               'TOOLS',     'PERSONALIZATION',
        'PRODUCTIVITY',           'PARENTING',             'WEATHER',
       'VIDEO_PLAYERS',  'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION',
                 '1.9']
Length: 34, dtype: str

34

In [10]:
d1['Genres'].value_counts()

Genres
Tools                       842
Entertainment               623
Education                   549
Medical                     463
Business                    460
                           ...
Strategy;Education            1
Racing;Pretend Play           1
Communication;Creativity      1
February 11, 2018             1
Strategy;Creativity           1
Name: count, Length: 120, dtype: int64

Selecting & Filtering data

In [12]:
print(d1['Content Rating'])
d1[['App', 'Rating']]

0          Everyone
1          Everyone
2          Everyone
3              Teen
4          Everyone
            ...
10836      Everyone
10837      Everyone
10838      Everyone
10839    Mature 17+
10840      Everyone
Name: Content Rating, Length: 10841, dtype: str

                                                     App  Rating
0         Photo Editor & Candy Camera & Grid & ScrapBook     4.1
1                                    Coloring book moana     3.9
2      U Launcher Lite – FREE Live Cool Themes, Hide ...     4.7
3                                  Sketch - Draw & Paint     4.5
4                  Pixel Draw - Number Art Coloring Book     4.3
...                                                  ...     ...
10836                                   Sya9a Maroc - FR     4.5
10837                   Fr. Mike Schmitz Audio Teachings     5.0
10838                             Parkinson Exercices FR     NaN
10839                      The SCP Foundation DB fr nn5n     4.5
10840      iHoroscope - 2018 Daily Horoscope & Astrology     4.5

[10841 rows x 2 columns]

In [15]:
print(d1.loc[2, 'App'])
d1.iloc[2,5]

U Launcher Lite – FREE Live Cool Themes, Hide Apps

'5,000,000+'

In [17]:
d1[d1['Category'] == 'GAME']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1653,ROBLOX,GAME,4.5,4447388,67M,"100,000,000+",Free,0,Everyone 10+,Adventure;Action & Adventure,"July 31, 2018",2.347.225742,4.1 and up
1654,Subway Surfers,GAME,4.5,27722264,76M,"1,000,000,000+",Free,0,Everyone 10+,Arcade,"July 12, 2018",1.90.0,4.1 and up
1655,Candy Crush Saga,GAME,4.4,22426677,74M,"500,000,000+",Free,0,Everyone,Casual,"July 5, 2018",1.129.0.2,4.1 and up
1656,Solitaire,GAME,4.7,254258,23M,"10,000,000+",Free,0,Everyone,Card,"August 1, 2018",2.137.0,4.1 and up
1657,Bubble Shooter,GAME,4.5,148897,46M,"10,000,000+",Free,0,Everyone,Casual,"July 17, 2018",1.20.1,4.0.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10791,Winter Wonderland,GAME,4.0,1287,38M,"50,000+",Free,0,Everyone,Word,"December 18, 2013",1.0,2.2 and up
10792,Soccer Clubs Logo Quiz,GAME,4.2,21661,16M,"1,000,000+",Free,0,Everyone,Trivia,"May 24, 2018",1.3.81,4.0 and up
10793,Sid Story,GAME,4.4,28510,78M,"500,000+",Free,0,Teen,Card,"August 1, 2018",2.6.6,4.0.3 and up
10803,Fatal Raid - No.1 Mobile FPS,GAME,4.3,56496,81M,"1,000,000+",Free,0,Teen,Action,"August 7, 2018",1.5.447,4.0 and up
10804,Poker Pro.Fr,GAME,4.2,5442,17M,"100,000+",Free,0,Teen,Card,"May 22, 2018",4.1.3,2.3 and up

In [19]:
d1[d1['Rating'].between(4.5, 5)]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up
13,Mandala Coloring Book,ART_AND_DESIGN,4.6,4326,21M,"100,000+",Free,0,Everyone,Art & Design,"June 26, 2018",1.0.4,4.4 and up
16,Photo Designer - Write your name with shapes,ART_AND_DESIGN,4.7,3632,5.5M,"500,000+",Free,0,Everyone,Art & Design,"July 31, 2018",3.1,4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10833,Chemin (fr),BOOKS_AND_REFERENCE,4.8,44,619k,"1,000+",Free,0,Everyone,Books & Reference,"March 23, 2014",0.8,2.2 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [ ]:
d1.sort_values()

In [20]:
d1.nlargest(5, 'Rating')

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN
329,Hojiboy Tojiboyev Life Hacks,COMICS,5.0,15,37M,"1,000+",Free,0,Everyone,Comics,"June 26, 2018",2.0,4.0.3 and up
612,American Girls Mobile Numbers,DATING,5.0,5,4.4M,"1,000+",Free,0,Mature 17+,Dating,"July 17, 2018",3.0,4.0.3 and up
615,Awake Dating,DATING,5.0,2,70M,100+,Free,0,Mature 17+,Dating,"July 24, 2018",2.2.9,4.4 and up
633,Spine- The dating app,DATING,5.0,5,9.3M,500+,Free,0,Teen,Dating,"July 14, 2018",4.0,4.0.3 and up

In [21]:
d1.groupby('Category')['Rating'].mean()

Category
1.9                    19.000000
ART_AND_DESIGN          4.358065
AUTO_AND_VEHICLES       4.190411
BEAUTY                  4.278571
BOOKS_AND_REFERENCE     4.346067
BUSINESS                4.121452
COMICS                  4.155172
COMMUNICATION           4.158537
DATING                  3.970769
EDUCATION               4.389032
ENTERTAINMENT           4.126174
EVENTS                  4.435556
FAMILY                  4.192272
FINANCE                 4.131889
FOOD_AND_DRINK          4.166972
GAME                    4.286326
HEALTH_AND_FITNESS      4.277104
HOUSE_AND_HOME          4.197368
LIBRARIES_AND_DEMO      4.178462
LIFESTYLE               4.094904
MAPS_AND_NAVIGATION     4.051613
MEDICAL                 4.189143
NEWS_AND_MAGAZINES      4.132189
PARENTING               4.300000
PERSONALIZATION         4.335987
PHOTOGRAPHY             4.192114
PRODUCTIVITY            4.211396
SHOPPING                4.259664
SOCIAL                  4.255598
SPORTS                  4.223511
TOOLS                   4.047411
TRAVEL_AND_LOCAL        4.109292
VIDEO_PLAYERS           4.063750
WEATHER                 4.244000
Name: Rating, dtype: float64

In [ ]:
d1.groupby('Rating').count()                            #makes rating like the index

,App,Category,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
Rating,,,,,,,,,,,,
1.0,16,16,16,16,16,16,16,16,16,16,16,16
1.2,1,1,1,1,1,1,1,1,1,1,1,1
1.4,3,3,3,3,3,3,3,3,3,3,3,3
1.5,3,3,3,3,3,3,3,3,3,3,3,3
1.6,4,4,4,4,4,4,4,4,4,4,4,4
1.7,8,8,8,8,8,8,8,8,8,8,8,8
1.8,8,8,8,8,8,8,8,8,8,8,8,8
1.9,13,13,13,13,13,13,13,13,13,13,13,13
2.0,12,12,12,12,12,12,12,12,12,12,12,12
2.1,8,8,8,8,8,8,8,8,8,8,8,8
2.2,14,14,14,14,14,14,14,14,14,14,14,14
2.3,20,20,20,20,20,20,20,20,20,20,20,20
2.4,19,19,19,19,19,19,19,19,19,19,19,19
2.5,21,21,21,21,21,21,21,21,21,21,21,21
2.6,25,25,25,25,25,25,25,25,25,25,25,25
2.7,25,25,25,25,25,25,25,25,25,25,25,25
2.8,42,42,42,42,42,42,42,42,42,42,42,42
2.9,45,45,45,45,45,45,45,45,45,45,45,45
3.0,83,83,83,83,83,83,83,83,83,83,83,83
3.1,69,69,69,69,69,69,69,69,69,69,69,69
3.2,64,64,64,64,64,64,64,64,64,64,63,64
3.3,102,102,102,102,102,102,102,102,102,102,102,102
3.4,128,128,128,128,128,128,128,128,128,128,128,128
3.5,163,163,163,163,163,163,163,163,163,163,163,163
3.6,174,174,174,174,174,174,174,174,174,174,174,174
3.7,239,239,239,239,239,239,239,239,239,239,239,239
3.8,303,303,303,303,303,303,303,303,303,303,303,303
3.9,386,386,386,386,386,386,386,386,386,386,386,386
4.0,568,568,568,568,568,568,568,568,568,568,567,568
4.1,708,708,708,708,708,708,708,708,708,708,707,708
4.2,952,952,952,952,952,952,952,952,952,952,951,952
4.3,1076,1076,1076,1076,1076,1076,1076,1076,1076,1076,1076,1076
4.4,1109,1109,1109,1109,1109,1109,1109,1109,1109,1109,1109,1108
4.5,1038,1038,1038,1038,1038,1038,1038,1038,1038,1038,1038,1037
4.6,823,823,823,823,823,823,823,823,823,823,823,823
4.7,499,499,499,499,499,499,499,499,499,499,499,499
4.8,234,234,234,234,234,234,234,234,234,234,234,234
4.9,87,87,87,87,87,87,87,87,87,87,87,87
5.0,274,274,274,274,274,274,274,274,274,274,274,274
19.0,1,1,1,1,1,1,1,0,1,1,1,0

In [23]:
d1['Reviews'].isna()

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840    False
Name: Reviews, Length: 10841, dtype: bool

In [24]:
d1['Rating'].mean()

np.float64(4.193338315362443)